// Code generated by autum framework annotation processor. DO NOT EDIT.
// versions:
//		go: go1.21.0
//		go-annotation: 0.1.0
//		autum framework: 0.1

package wire

import (
	"github.com/gosrob/autumn/examples/beandefinition"
	"github.com/gosrob/autumn/examples/beandefinition/subdirectory"
	"github.com/gosrob/autumn/pkg/container"
	"github.com/samber/do/v2"
)

func init() {
	var1_lwcNO := subdirectory.C{}
	var1_eVskv := beandefinition.DefinitionDemo{}
	var1_LcaGb := beandefinition.Interfacea{}
	var1_dwXFa := *beandefinition.ProduceDefinitionDemo(&var1_lwcNO)

	var1_eVskv.B = var1_dwXFa

	var1_eVskv.Inter = append(var1_eVskv.Inter, &var1_lwcNO)

	var1_eVskv.Inter = append(var1_eVskv.Inter, &var1_LcaGb)

	do.ProvideNamedValue(container.Container, "github.com/gosrob/autumn/examples/beandefinition/subdirectory.C", var1_lwcNO)

	do.ProvideNamedValue(container.Container, "github.com/gosrob/autumn/examples/beandefinition.DefinitionDemo", var1_eVskv)

	do.ProvideNamedValue(container.Container, "github.com/gosrob/autumn/examples/beandefinition.Interfacea", var1_LcaGb)

	do.ProvideNamedValue(container.Container, "github.com/gosrob/autumn/examples/beandefinition/subdirectory.B", var1_dwXFa)
}
