// Code generated by autum framework annotation processor. DO NOT EDIT.
// versions:
//		go: go1.21.0
//		go-annotation: 0.1.0
//		autum framework: 0.1

package wire

import (
	"github.com/gosrob/autumn/testdata/beandefinition"
)

func init() {

	var1_mPCRM := beandefinition.DefinitionDemo{}
	var1_wSXLM := *beandefinition.ProduceDefinition()
	var1_XwvIA := *beandefinition.ProduceDefinitionDemo()

	var1_mPCRM.B = var1_XwvIA
}
