// Code generated by autum framework annotation processor. DO NOT EDIT.
// versions:
//		go: go1.21.0
//		go-annotation: 0.1.0
//		autum framework: 0.1

package wire

import (
	"github.com/gosrob/autumn/examples/beandefinition"
	"github.com/gosrob/autumn/examples/beandefinition/subdirectory"
	"github.com/gosrob/autumn/pkg/container"
	"github.com/samber/do/v2"
)

func init() {

	var1_YYRDj := subdirectory.C{}
	var1_zDknA := beandefinition.DefinitionDemo{}
	var1_qXhPI := *beandefinition.ProduceDefinitionDemo(&var1_YYRDj)

	var1_zDknA.B = var1_qXhPI

	var1_zDknA.Inter = append(var1_zDknA.Inter, &var1_YYRDj)

	do.ProvideNamedValue(container.Container, "github.com/gosrob/autumn/examples/beandefinition/subdirectory.C", var1_YYRDj)

	do.ProvideNamedValue(container.Container, "github.com/gosrob/autumn/examples/beandefinition.DefinitionDemo", var1_zDknA)

	do.ProvideNamedValue(container.Container, "github.com/gosrob/autumn/examples/beandefinition/subdirectory.B", var1_qXhPI)

}
